### PR TITLE
[SNAP-8809] [Part 1] Remove logback dependency from anaplan java client

### PR DESCRIPTION
**Pull request by Syed-SnapLogic**

### CODE REVIEW

**Comment by ravimergu1** [comment]
Replaced logback-classic dependency with slf4j-api dependency and removed logback related code.

checked this anaplan-java-client dependency with anaplan snaps working fine as expected and logs also storing in jcc.json file.

Screenshot from 2021-12-22 16-12-48

Screenshot from 2021-12-22 16-11-00

**Comment by robinhowlett** [comment]
@Syed-SnapLogic @ravimergu1 was any analysis done on the upstream repo?

**Review by pmeister — APPROVED** [review]
LGTM

**Review by alex-rentz — APPROVED** [review]

**Comment by Syed-SnapLogic** [comment]
@robinhowlett , @ravimergu1 is going to check the latest version of the anaplan-java-client repo and provide us with his findings.

**Comment by ravimergu1** [comment]
@robinhowlett  For anaplan-java-client there is no new version after mar-2020 and using old version of logback dependency (ch.qos.logback:logback-classic:1.2.3)

**Pull request merged**
